name: Build server1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [34.207.146.6, 54.210.177.62]
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build docker image
      #   uses: hoverkraft-tech/compose-action@v2.0.1
      #   with:
      #     compose-file: "./compose.yaml"
      #     up-flags: "--build -d"

      - name: Run docker compose up --build
        run: docker compose up --build && docker compose down

      - name: Tag the docker image
        run: docker tag mockstack-overflow-web ${{ secrets.DOCKER_USERNAME }}/mockstack-overflow-web:latest

      - name: Publish image to docker hub
        run: docker push fifss/mockstack-overflow-web:latest

      # - name: Setup SSH for EC2
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Login to servers
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
            EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
            EC2_URL: ${{ matrix.server }}

      - name: Run docker commands on server 1 & 2
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@${{ matrix.server }} << EOF
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            cd /home/ubuntu/MockStack-overflow
            docker pull $DOCKER_USERNAME/mockstack-overflow-web:latest
            docker run -d --name mockstack-overflow-web -p 8000:8000 $DOCKER_USERNAME/mockstack-overflow-web:latest
          EOF
        
      # - name: Run docker compose up -d
      #   uses: alex-ac/github-action-ssh-docker-compose@master
      #   with:
      #       ssh_host: ${{ matrix.server }}
      #       ssh_private_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      #       ssh_user: ${{ secrets.EC2_USERNAME }}
      #       docker_compose_prefix: mockstack-overflow-web
            # docker_compose_down: 'false'
    
    # docker stop mockstack-overflow-web || true
    # docker rm mockstack-overflow-web || true