name: Build server1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [54.167.38.176, 3.92.79.1]
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      # EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yaml"
          up-flags: "--build -d"

      - name: Tag the docker image
        run: docker tag mockstack-overflow-web ${{ secrets.DOCKER_USERNAME }}/mockstack-overflow-web:latest

      - name: Publish image to docker hub
        run: docker push fifss/mockstack-overflow-web:latest

      - name: Setup SSH for EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # - name: Add EC2 host to known hosts
      #   run: ssh-keyscan -H "${{ matrix.hosts }}" >> ~/.ssh/known_hosts

      - name: Login to servers
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
            EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
            EC2_URL: ${{ matrix.hosts }}

      - name: Run docker commands on server 1
        run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@${{ matrix.server }} << 'EOF'
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker pull ${{ secrets.DOCKER_USERNAME }}/mockstack-overflow-web:latest
                  docker compose up -d
                EOF



        # run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL << 'EOF'
        #         cd /home/ubuntu
        #         rm -rf MockStack-overflow
        #         git clone https://github.com/oluwabunmifife/MockStack-overflow.git
        #         cd /home/ubuntu/MockStack-overflow
        #         docker compose up --build -d
        #       EOF