name: Build server1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    strategy:
      matrix:
        hosts: [secrets.EC2_URL, secrets.EC2_HOST_2]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        uses: hoverkraft-tech/compose-action@v0.0.0
        with:
          compose-file: "./compose.yaml"
          up-flags: "--build -d"

      - name: Publish image to docker hub
        run: docker push mockstack-overflow:latest

      - name: Login to servers
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
            EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
            EC2_URL: ${{ matrix.hosts }}

      - name: Run docker commands on server 1
        run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL << 'EOF'
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker pull fifss/mockstack-overflow:latest
                  docker compose up -d



        # run: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL << 'EOF'
        #         cd /home/ubuntu
        #         rm -rf MockStack-overflow
        #         git clone https://github.com/oluwabunmifife/MockStack-overflow.git
        #         cd /home/ubuntu/MockStack-overflow
        #         docker compose up --build -d
        #       EOF